[font]
size = 10

[font.bold]
family = "Fira Code Nerd Font"

[font.bold_italic]
family = "Fira Code Nerd Font"

[font.italic]
family = "Fira Code Nerd Font"

[font.normal]
family = "Fira Code Nerd Font"
