local awful = require("awful")
-- awful.spawn.with_shell("feh --bg-scale -r -z ~/Images/Wallpapers/Landscape/")
awful.spawn.with_shell("picom")
awful.spawn.with_shell("caffeine")
awful.spawn.with_shell("xset s 300 300 && xautolock -time 15 -locker 'systemctl suspend' -detectsleep")

awful.spawn.with_shell("nm-applet")
awful.spawn.with_shell("blueberry-tray")
awful.spawn.with_shell("cbatticon")
awful.spawn.with_shell("python3 ~/.config/awesome/random_wallpaper.py")
-- awful.spawn.with_shell("~/.config/awesome/polybar/launch.sh")
