local awful = require("awful")
-- awful.spawn.with_shell("feh --bg-scale -r -z ~/Images/Wallpapers/Landscape/")
awful.spawn.with_shell("picom")
awful.spawn.with_shell("nm-applet")
awful.spawn.with_shell("killall cbatticon && cbatticon")
awful.spawn.with_shell("python3 ~/.config/awesome/random_wallpaper.py")
-- awful.spawn.with_shell("~/.config/awesome/polybar/launch.sh")
