#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding         26

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#Autostart applications
lsxhkd &
# picom --config $Home/.config/picom/picom.conf &
picom &
dunst &
nm-applet &
killall polybar
polybar &
# sh ~/.config/bspwm/random_wallpaper.sh &
wal -i $(python ~/.config/bspwm/random_wallpaper.py) 
